# Generated by Django 4.2.25 on 2025-10-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('tracks', models.PositiveIntegerField(default=0)),
                ('country', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['artist', 'year', 'title'],
                'unique_together': {('title', 'artist', 'year')},
            },
        ),
    ]
