# Generated by Django 4.2.25 on 2025-10-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='album',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='album',
            name='tracks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.IntegerField(),
        ),
    ]
